import type { Metadata } from "next";
import { Geist, Geist_Mono, Grenze, Nova_Square } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";



const novaSquare = Nova_Square({
  variable: "--font-nova-square",
  subsets: ["latin"],
  weight: "400",});

const grenze = Grenze({
  variable: "--font-grenze",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={` ${novaSquare.variable} ${grenze.variable} antialiased`}
      >
        {children}
        <Toaster position="top-center" richColors closeButton />
      </body>
    </html>
  );
}
